import json
import os
import pandas as pd

import main


models = ["chatgpt"]
tasks_filename ="task_names_test.json"

opt = main.parse_opt()
opt.llm = None
opt.env = None
opt.num_episodes = 2
opt.step = -1 # -1 means use the plan step generated by the llm
opt.erci = 1
opt.irci = 3
opt.sgrounding = True
opt.headless = True
with open(tasks_filename) as f:
    task_names = json.load(f)["task_name"]

setattr(opt, "models", models)
setattr(opt, "task_names", task_names)

filename = "arguments.json"
with open(filename, "w") as f:
    json.dump(vars(opt), f)

columns = ["model name", "task_name", "success_rate", "min_sent", "max_sent", "mean_sent", "min_received", "max_received", "mean_received", "mean_calls"]
df = pd.DataFrame(columns=columns)

for model in models :
    print("Using model : ", model)
    opt.llm = model
    for task_name in task_names :
        opt.env = task_name     # switch task
        print("     Task addressed : ", opt.env)
        print(opt)
        result = main.miniwob(opt)
        
        df.loc[len(df)] = [model, task_name, result["success_rate"], result["min_sent"], result["max_sent"], result["mean_sent"], result["min_received"], result["max_received"], result["mean_received"], result["mean_calls"]]

filename = "result.json"
if os.path.exists(filename):
    os.remove(filename)
df.to_json(filename, mode="w")